#!/bin/bash

git fetch
git co develop

git pr
git br -d $1

if [ $? -eq 0 ]; then
  echo "Successfully created file"
else
  echo "Remove the branch whatever [y|n]?:"
  read RM_BRANCH
  if [ "$RM_BRANCH" = "n" ]; then
    echo "Script exit because of no resolution of branch deletion" >&2
    exit
  fi
  git br -D $1
fi

git co $1
git pr
git rb origin/develop
git lga -20
npm install
gulp svg build:dev
